
import "../globals.css";
import Sidebar from "@/components/sidebar/Sidebar";
import Provider from "@/providers/MainProvider";
import {getServerSession} from "next-auth";
import {ToastContainer} from "react-toastify";
import 'react-confirm-alert/src/react-confirm-alert.css';
import 'react-date-picker/dist/DatePicker.css';
import "react-datepicker/dist/react-datepicker.css";
import "plyr-react/plyr.css";
import 'react-calendar/dist/Calendar.css';
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import {authOptions} from "@/app/api/auth/[...nextauth]/route";
import {validateToken} from "@/utils/api/auth";
import {redirect} from "next/navigation";
import MobileSidebarOverlay from "@/components/sidebar/MobileSidebarOverlay";
export const metadata = {
    title: "LMS Admin",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    const session = await getServerSession(authOptions);

    try {
        await validateToken();
    } catch (e) {
        redirect(`/login`);
    }

    return (
        <div className=" bg-cover bg-center ">
            <Provider session={session}>
                <div id="wrapper">
                    <MobileSidebarOverlay />
                    <Header/>
                    <Sidebar />
                        {children}
                    <Footer/>
                </div>
                <ToastContainer toastClassName="bg-[#fff] text-[#000] text-[17px]" />
            </Provider>
        </div>
    );
}
